### ISSUE TITLE
How to use it.

### ISSUE THREAD

**Issue by Sadmansamee** [parse-server-modules/parse-server-firebase-auth-adapter#1]
How to use this adapter? any readme or anything?

**Comment by ranhsd** [comment]
Hi ,
I need to write some guide on how exactly to use it. I didn't find some time yet but i will do it soon. 

The main idea is to use it exactly the same way you use any other auth provider. 
1. Add **firebase** provider to your config auth list, add your firebase databaseURL and firebase credential JSON file path

 ```
   "auth" : {
        "firebase" : {
            "module" : "parse-server-firebase-auth-adapter",
            "databaseURL" : "https:/*****.firebaseio.com",
            "credential" : "/parse-server/keys/firebase/*****.json"
        }
    }  
```

2. Add firebase SDK to your client (currently i am doing it only in iOS but it should be similar steps for android as well) described in here: https://firebase.google.com/docs/ios/setup

3. Sign in or sign Up or login with facebook, google etc. your user by reading the steps described in here: https://firebase.google.com/docs/auth/ios/password-auth 

4. post signing in you have an access token. This access token should be sent to parse via parse SDK. this can achieve via parse SDK by using the **logInWithAuthTypeInBackground** there you need to pass the id of the user in firebase and the auth_token 

You can look at an example in here: https://gist.github.com/flovilmart/68a6c538496953408bb1

Anyway, if you still don't manage to do it please let me know and i will do my best to add it to the README asap.

**Comment by Sadmansamee** [comment]
thank you very much

**Comment by ranhsd** [comment]
Sure, meantime I close this issue. If you have any further questions pleas feel free to open a new issue.
